project 'Buzzni.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Buzzni' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buzzni
  pod 'RxSwift', '6.0.0-rc.2'
  pod 'RxCocoa', '6.0.0-rc.2'

  target 'BuzzniTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuzzniUITests' do
    # Pods for testing
  end

end
